easy_admin:
    entities:
        Product:
            class: App\Entity\Product
            list:
                actions:
                   - {name: 'edit', icon: 'pencil', label: false, css class: 'btn btn-secondary'}
                   - {name: 'delete', icon: 'trash', label: false, css class: 'btn btn-danger'}
                fields: ['name','','description','price','createdAt', 'updateAt',{property: 'image', type: 'image' base_path: '../%uploads_path%'} ]
            form:


